export const items = [
  {
    id: 1,
    purchase_name: "blue",
    src: "/jelly_guy_blue.png",
    alt: "blue-bean",
    category: "skins",
    price: 20,
  },
  {
    id: 2,
    purchase_name: "green",
    src: "/jelly_guy_green.png",
    alt: "green-bean",
    category: "skins",
    price: 20,
  },
  {
    id: 3,
    purchase_name: "red",
    src: "/jelly_guy_red.png",
    alt: "red-bean",
    category: "skins",
    price: 20,
  },
  {
    id: 4,
    purchase_name: "yellow",
    src: "/yellowjelly/yellowJelly_resize.png",
    alt: "jellies",
    category: "skins", //is it really a skin?
    price: 20,
  },
  {
    id: 5,
    purchase_name: "Chef Hat",
    src: "/chef_hat.png",
    alt: "chef hat",
    price: 35,
    category: "hats",
  },
  {
    id: 6,
    purchase_name: "Sheriff Hat",
    src: "/sheriff_hat_right.png",
    alt: "sheriff hat",
    price: 35,
    category: "hats",
  },
  {
    id: 7,
    purchase_name: "Mexican Hat",
    src: "/mexican_hat.png",
    alt: "amigos mexican sombrero",
    price: 35,
    category: "hats",
  },
  {
    id: 8,
    purchase_name: "Yellow and Chef Hat",
    src: "/yellowjelly/yellowJelly_chefHat.png",
    alt: "a yellow jelly wearing a chef hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 9,
    purchase_name: "Mexican Yellow Jelly",
    src: "/yellowjelly/yellowJelly_mexicanHat_moustache.png",
    alt: "a mexican yellow jelly with moustache wearing a chef hat",
    price: 90,
    category: "premium skins",
  },
  {
    id: 10,
    purchase_name: "Yellow and Sheriff Hat",
    src: "/yellowjelly/yellowJelly_sheriffHat.png",
    alt: "a yellow jelly wearing a sheriff hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 11,
    purchase_name: "Blue and Chef Hat",
    src: "/bluejelly/blue_chefHat.png",
    alt: "a blue jelly wearing a chef hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 12,
    purchase_name: "Blue and Mexican Hat",
    src: "/bluejelly/blue_mexicanHat.png",
    alt: "a blue jelly wearing a mexican hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 13,
    purchase_name: "Blue and Sheriff Hat",
    src: "/bluejelly/blue_sheriffHat.png",
    alt: "a blue jelly wearing a sheriff hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 14,
    purchase_name: "Green and Chef Hat",
    src: "/greenjelly/green_chefHat.png",
    alt: "a green jelly wearing a chef hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 15,
    purchase_name: "Green Sheriff Jelly in Mars",
    src: "/greenjelly/green_mars_sheriff_moustache.jpg",
    alt: "a green jelly wearing a chef hat",
    price: 90,
    category: "premium skins",
  },
  {
    id: 16,
    purchase_name: "Green and Mexican Hat",
    src: "/greenjelly/green_mexicanHat.png",
    alt: "a green jelly wearing a mexican hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 17,
    purchase_name: "Red and Chef Hat",
    src: "/redjelly/jelly_guy_red_chefHat.png",
    alt: "a red jelly wearing a chef hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 18,
    purchase_name: "Red and Mexican Hat",
    src: "/redjelly/jelly_guy_red_mexicanHat.png",
    alt: "a red jelly wearing a mexican hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 19,
    purchase_name: "Red Chef Jelly in a Madow",
    src: "/redjelly/redJelly_chef_meadow.png",
    alt: "a chef red jelly bean in a meadow",
    price: 90,
    category: "premium skins",
  },
  {
    id: 20,
    purchase_name: "Purple and Chef Hat",
    src: "/purplejelly/jelly_guy_purple_chef.png",
    alt: "a purple jelly wearing a chef hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 21,
    purchase_name: "Purple and Mexican Hat",
    src: "/purplejelly/jelly_guy_purple_mex.png",
    alt: "a purple jelly wearing a Mexican hat",
    price: 50,
    category: "skins and hats",
  },
  {
    id: 22,
    purchase_name: "Purple and Sheriff Hat",
    src: "/purplejelly/jelly_guy_purple_sheriff.png",
    alt: "a purple jelly wearing a Sheriff hat",
    price: 50,
    category: "skins and hats",
  },
  
];

export const sections = [
  {
    id: 1,
    name: "social",
    categories: ["Drinking", "Eating Out", "Travel", "Occasions", "Holiday"],
  },
  {
    id: 2,
    name: "financial",
    categories: [
      "Interest Rates",
      "Currency",
      "Mortgages",
      "Charity",
      "Savings",
    ],
  },
  {
    id: 3,
    name: "wellbeing",
    categories: ["Health", "Exercise", "Nutrition", "Mindfulness", "Weight"],
  },
  {
    id: 4,
    name: "general",
    categories: [
      "Addition",
      "Subtraction",
      "Multiplication",
      "Division",
      "Further",
    ],
  },
  {
    id: 5,
    name: "home",
    categories: ["Gardening", "Shopping", "Cooking", "Chores", "DIY"],
  },
];
